name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
      - run: npm install        
      - run: npx cypress run
      - name: Prepare reports
        if: always()
        run: |
          cd frontend
          npm i -g mochawesome-merge
          npm i -g mochawesome-report-generator
          mochawesome-merge test/cypress/reports/mocha/*.json > ./test/cypress/reports/mocha/index.json
          marge --charts=true --showPassed=false -o ./test/cypress/reports/mocha/ ./test/cypress/reports/mocha/index.json
      - name: Cypress report
        uses: dmitry/cypress-report-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pathname: frontend/test/cypress/reports/mocha/index.json
        if: always()    